[theme]
base = "dark"
primaryColor = "#E9001C"
backgroundColor = "#13131A"
secondaryBackgroundColor = "#1E1E2B"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false